---

name: AutoDeploy to gh-pages

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          branch: master
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '${{ matrix.node-version }}'
      - name: 'Yarn install, test, build and deploy'
        run: >
          git config --global user.name "${{ secrets.GIT_AUTHOR_NAME }}"

          git config --global user.email "${{ secrets.GIT_AUTHOR_EMAIL }}"

          yarn install

          yarn test

          git clone -b gh-pages --single-branch https://${{ secrets.GITHUB_TOKEN
          }}@github.com/janbaer/mdwiki.git deploy

          yarn deploy
        env:
          CI: true
      - name: Push changes to branch gh-pages
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: /home/runner/work/mdwiki/mdwiki/deploy
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: gh-pages
      - name: Trigger a new build of gh-pages
        run: >
          curl -X POST \
          --header 'Accept: application/vnd.github.mister-fantastic-preview+json' \
          -u janbaer:${{ secrets.ACCESS_TOKEN}}                                   \
          'https://api.github.com/repos/janbaer/mdwiki/pages/builds'
