name: AutoDeploy to gh-pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
      with:
        branch: master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn install, test, build and deploy
      run: |
        git config --global user.name "${{ secrets.GIT_AUTHOR_NAME }}"
        git config --global user.email "${{ secrets.GIT_AUTHOR_EMAIL }}"
        yarn install
        yarn test
        git clone -b gh-pages --single-branch https://${{ secrets.GITHUB_TOKEN }}@github.com/janbaer/mdwiki.git deploy
        yarn deploy
      env:
        CI: true
    - uses: ad-m/github-push-action@v0.5.0
      if: github.ref == 'refs/heads/master'
      with:
        directory: /home/runner/work/mdwiki/mdwiki/deploy
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
